SELECT ?title ?venue
WHERE {
	?venue dc:title ?title ;
	FILTER (langMatches(lang(?title), "nl"))   
	{
		SELECT DISTINCT ?venue
		WHERE {
			?venue a ah:Venue ;
				ah:locationAddress ?address .	
			?address vcard:locality ?city .
	
			?event a ah:Event ;
				ah:venue ?venue ;
				time:hasBeginning ?date .

			FILTER (?date >= "2012-11-01"^^xsd:dateTime)
			FILTER (?date < "2012-11-08"^^xsd:dateTime)
		} 
		GROUP BY ?venue 
		ORDER BY DESC(?events)
		LIMIT 10
	}
}