PREFIX ah: <http://purl.org/artsholland/1.0/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?city (COUNT(?event) AS ?events)
WHERE {
	?event a ah:Event ;
		ah:venue ?venue ;
		time:hasBeginning ?date .

	?venue ah:locationAddress ?address .

	?address vcard:locality ?city .

	FILTER (?date >= "??date_start"^^xsd:dateTime)
	FILTER (?date < "??date_end"^^xsd:dateTime)
} 
GROUP BY ?city
ORDER BY DESC(?events)
LIMIT 4