PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?class_label ?class (COUNT(?class) AS ?count)
WHERE {
  [] a ?class .
  ?class rdfs:label ?class_label .  
} 
GROUP BY ?class ?class_label
ORDER BY DESC(?count)
LIMIT 5