PREFIX ah: <http://purl.org/artsholland/1.0/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
SELECT ?event ?venue ?production ?lat ?long ?venueTitle ?productionTitle ?date ?city
WHERE {
	
	?event a ah:Event .
	?event ah:venue ?venue .
	?event ah:production ?production .
	
	?venue geo:lat ?lat .
	?venue geo:long ?long .
	
	?venue ah:locationAddress ?address .
	?address vcard:locality ?city .
	
	?venue dc:title ?venueTitle .
	?production dc:title ?productionTitle .
	
	?event time:hasBeginning ?date .
	FILTER (?date >= "2012-10-03T00:00:00Z"^^xsd:dateTime) .
	FILTER (?date <= "2012-10-10T23:59:59Z"^^xsd:dateTime) .
	
	FILTER langMatches( lang(?venueTitle), "nl" ) .
	FILTER langMatches( lang(?productionTitle), "nl" ) .
	
} ##LIMIT 30